In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,10)

In [3]:
arr1=arr1.reshape(3,3)

In [5]:
arr2=np.arange(11,20)
arr2=arr2.reshape(3,3)

In [6]:
arr1+arr2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [8]:
arr=np.array([1,2,3,4,5,0])
np.where(arr==0)

(array([5], dtype=int64),)

In [11]:
zero=np.zeros(10)

In [12]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
ones=np.ones(10)

In [14]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
fives=np.ones(10)*5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [17]:
l1=[i for i in range(30,71) if i%2==0]

In [19]:
even=np.array(l1)
even

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [20]:
iden=np.identity(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
linespace=np.linspace(0,1,10)
linespace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
vector=np.arange(10,22).reshape(3,4)
print(vector)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [27]:
vector.flat
for i in vector.flat:
    print(i)

10
11
12
13
14
15
16
17
18
19
20
21


In [28]:
vec1=np.linspace(5,50,10)

In [29]:
vec1

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [31]:
vec2=np.arange(21)
vec2.flat
for i in vec2.flat:
    if (i>=9)&(i<=15):
        vec2[i]=vec2[i]*-1

        
vec2        

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [32]:
x = np.ones((10, 10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
ran=np.random.random((3,3,3))
ran

array([[[0.12514636, 0.81502895, 0.71799972],
        [0.46553883, 0.63071512, 0.04912914],
        [0.26844946, 0.43117643, 0.24280393]],

       [[0.68030736, 0.41605915, 0.62528339],
        [0.99910749, 0.59606502, 0.43279798],
        [0.37056151, 0.75878971, 0.42891266]],

       [[0.23457898, 0.31097314, 0.90197624],
        [0.16318785, 0.41861059, 0.58619651],
        [0.31440701, 0.69766411, 0.98104728]]])