# Numpy Tutorial


In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,6,32,7]],np.int8)

In [3]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape 

(1, 4)

In [6]:
 myarr[0,1]=45

In [7]:
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

# Array creation:Conversion from other Python structures 

In [8]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.dtype

dtype('int32')

In [11]:
zeros=np.zeros((2,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
 rng=np.arange(15)

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
print(type(rng))

<class 'numpy.ndarray'>


In [16]:
lspace=np.linspace(1,4,4)

In [17]:
lspace

array([1., 2., 3., 4.])

In [18]:
emp=np.empty((4,6))

In [19]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90108992e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

In [20]:
emp_like=np.empty_like(lspace)

In [21]:
emp_like

array([1., 2., 3., 4.])

In [22]:
ide=np.identity(45)

In [23]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [24]:
arr=np.arange(99)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
 arr=arr.reshape(3,33)

In [27]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr=arr.ravel()

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr.shape

(99,)

In [31]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [32]:
ar=np.array(x)

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar.sum(axis=0)

array([12, 15, 18])

In [35]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
  ar.flat

In [37]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [38]:
ar.ndim

2

In [39]:
ar.size

9

In [40]:
ar.nbytes

36

In [41]:
 ar.argmax()

8

In [42]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [43]:
ar.argmin()

0

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [46]:
 ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [47]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [48]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
ar2=np.array([[1, 2, 3],
       [4, 0, 6],
       [8, 1, 9]])

In [52]:
ar2

array([[1, 2, 3],
       [4, 0, 6],
       [8, 1, 9]])

In [53]:
ar+ar2

array([[ 2,  4,  6],
       [ 8,  5, 12],
       [15,  9, 18]])

In [54]:
  ar*ar2

array([[ 1,  4,  9],
       [16,  0, 36],
       [56,  8, 81]])

In [55]:
 np.sqrt(ar2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 3.        ]])

In [56]:
ar2

array([[1, 2, 3],
       [4, 0, 6],
       [8, 1, 9]])

In [57]:
ar2.sum()

34

In [58]:
ar2.max()

9

In [59]:
ar2.min()

0

In [60]:
 np.where(ar2>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 2], dtype=int64))

In [61]:
 np.count_nonzero(ar2)

8

In [62]:
 np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1, 2], dtype=int64))

In [63]:
import sys

In [64]:
py_ar=[0,4,55,2]

In [65]:
np_ar=np.array(py_ar)

In [66]:
sys.getsizeof(1)*len(py_ar)

112

In [67]:
np_ar.itemsize*np_ar.size

16

In [70]:
a=int(input())
print(a)

4
